[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string] $SourceDirectory,
    [Parameter(Mandatory = $true)][string] $OutputPath,
    [ValidateSet('violet', 'indigo', 'blue', 'cyan', 'teal', 'green', 'orange')][string] $Accent = 'violet'
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Fujin.Common.ps1')
$root = Split-Path $PSScriptRoot -Parent
$lock = Get-FujinLock (Join-Path $root 'third_party/fujin/lock.json')
Assert-FujinCheckout $SourceDirectory $lock
$data = Read-FujinThemeData $SourceDirectory $lock
function ConvertTo-NativeColor([string] $Color) {
    return ('RGB(0x{0},0x{1},0x{2})' -f $Color.Substring(1,2), $Color.Substring(3,2), $Color.Substring(5,2))
}
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// Generated by tools/generate-theme.ps1; do not edit.')
$lines.Add("// Fujin $($lock.tag), commit $($lock.commit), accent $Accent.")
$lines.Add('// Included inside namespace dac after windows.h.')
$lines.Add('/*')
$lines.Add((Get-Content -LiteralPath (Join-Path $SourceDirectory 'LICENSE') -Raw).Trim())
$lines.Add('*/')
$lines.Add('namespace fujin {')
$lines.Add('struct Palette { COLORREF base,surface,elevated,text,secondary,onAccent,border,strong,accent,hover,active,chrome,chromeText; };')
foreach ($mode in @('dark', 'light')) {
    $colors = @()
    foreach ($pair in $data.Roles.GetEnumerator()) {
        $value = $data.Json.$mode.($pair.Value)
        switch ($pair.Key) {
            'accent' { $value = $data.Accents[$Accent][0] }
            'hover' { $value = $data.Accents[$Accent][1] }
            'active' { $value = $data.Accents[$Accent][2] }
        }
        $colors += ConvertTo-NativeColor $value
    }
    $lines.Add("inline constexpr Palette $mode={$($colors -join ',')};")
}
foreach ($pair in $data.Scalars.GetEnumerator()) { $lines.Add("inline constexpr int $($pair.Key)=$($pair.Value);") }
$lines.Add('inline constexpr wchar_t fontFamily[]=L"' + $data.FontFamily + '";')
$lines.Add('inline constexpr wchar_t accentName[]=L"' + $Accent + '";')
$lines.Add('inline constexpr char sourceCommit[]="' + $lock.commit + '";')
$lines.Add('} // namespace fujin')
$content = ($lines -join "`n") + "`n"
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
New-Item -ItemType Directory -Path (Split-Path $OutputPath -Parent) -Force | Out-Null
if (-not (Test-Path -LiteralPath $OutputPath) -or [IO.File]::ReadAllText($OutputPath) -cne $content) {
    [IO.File]::WriteAllText($OutputPath, $content, [Text.UTF8Encoding]::new($false))
}
Write-Output "Verified Fujin $($lock.tag); native theme ready: $OutputPath"
